services:

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      PORT: 4001
      JWT_SECRET: dev_jwt_secret
    ports:
      - "4001:4001"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    environment:
      PORT: 4002
      AUTH_SERVICE_URL: http://auth-service:4001
      NOTIFICATION_SERVICE_URL: http://notification-service:4003
    ports:
      - "4002:4002"
    depends_on:
      - auth-service
      - notification-service

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    environment:
      PORT: 4003
    ports:
      - "4003:4003"